name: Python Scaffold Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install pyyaml

    - name: Syntax check
      run: python -m py_compile scaffold.py

    - name: Run tests
      run: |
        echo "🧪 No test suite yet. Add unit tests in tests/ folder."
